# -*- coding: utf-8 -*-
"""MLFlow01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18-yE3cVsV2FsSplTAamPqY_dbFwp-9qj
"""

#!pip install mlflow
import mlflow
mlflow.set_experiment("mlflow_test")

import mlflow
mlflow.set_experiment("mlflow_test")

"""anything called after this line gets locked into this experiment"""

with mlflow.start_run():
  mlflow.log_param('categories', {"cat","dog","cheetah"})

"""The with mlflow.start_run(): statement initiates a new MLflow run, which acts as a container for all the information related to a single execution of your machine learning code. Inside this run, mlflow.log_param('categories', {"cat","dog","cheetah"}) logs a specific parameter. In this case, it's logging a parameter named 'categories' and assigning it the value of the set {"cat","dog","cheetah"}. Parameters are typically used to record configuration settings, hyperparameters, or any other static key-value information relevant to your experiment."""